name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
        working-directory: packages/emoji-picker-react

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: npm publish
        working-directory: packages/emoji-picker-react
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}