name: Validations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
        working-directory: packages/emoji-picker-react
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
        working-directory: packages/emoji-picker-react
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
        working-directory: packages/emoji-picker-react